version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
  port_domain_service:
    build: ./port_domain_service
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    links:
      - 'mongo:db'
  client_api:
    depends_on:
      - port_domain_service
    build: ./client_api
    ports:
      - "8080:8080"
    links:
      - 'port_domain_service:pds'
